apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
spec:
  project: default
  source:
    repoURL: hhttps://github.com/CloudSculptorProject/CloudSculptorAPP.git
    targetRevision: main
    path: /charts/
    helm:
      values: |
        replicaCount: 2
        service:
          port: 8081
          targetPort: 8081
  destination:
    server: https://aks01-dns-gul8e4b6.hcp.eastus.azmk8s.io:443
    namespace: default
  syncPolicy:
    automated: {}
