apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CloudSculptorProject/CloudSculptorAPP.git
    path: CloudSculptorAPP/Argo CD/helm-webapp/templates
    targetRevision: HEAD
  destination:
    server: https://aks01-dns-gul8e4b6.hcp.eastus.azmk8s.io:443
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
