apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html  # Directorio donde se servirá el HTML
  volumes:
  - name: html-volume
    gitRepo:
      repository: "https://github.com/tuusuario/turepositorio.git"  # URL de tu repositorio
      directory: "Definición de APP CS/CloudSculptorWEB"  # Ruta al directorio que contiene tu aplicación HTML
      revision: main  # Rama o commit específico a usar
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hello-world
